version: '3.8'

services:
  api_patrimony:
    container_name: backend_patrimony
    build: .
    ports:
      - 3006:3006
    environment: 
      PORT: 3006
    env_file: .env
    volumes:
      - ./:/code
      - node_modules:/code/node_modules
    networks: 
      - backend_patrimony
    depends_on:
      - db_patrimony

  db_patrimony:
    container_name: db_patrimony
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    env_file: .env
    volumes:
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db/.dbshell:/home/mongodb/.dbshell
      - mongodb:/data/db
    networks: 
      - backend_patrimony

volumes: 
  node_modules:
  mongodb:

networks: 
  backend_patrimony: